import { Inter } from "next/font/google";
import LongLogo from "@/LongLogo.svg";
import subLogo from "@/subLogo.svg";
import Image from "next/image";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="h-dvh"
        style={{
          background:
            "linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, #e8f0fe 100%)",
        }}
      >
        <div className="flex flex-col gap-6 justify-center items-center mt-10 mb-10">
          <Image src={LongLogo} alt="longLogo" width={200} height={200} />
          <Image src={subLogo} alt="longLogo" width={350} height={350} />
        </div>
        {children}
      </body>
    </html>
  );
}
